### ISSUE TITLE
https://www.formium.net/ not working

### ISSUE THREAD

**Issue by jacobSpitzer** [NetDimension/NanUI#179]
The https://www.formium.net/ documentation site is down.

**Comment by XuanchenLin** [comment]
Yes, I closed it few month ago. This site was written in Chinese and it only provided one feature the documentation of NanUI. Due to something I can't say, I had to close this site. But you can still find everything you need as https://github.com/NetDimension/NanUI/blob/master/docs/documentation.md or http://docs.formium.net
